### PR TITLE
Fix missing required field

### PR DESCRIPTION
**Pull request by Snipeur060**
I add channelId is not specified but is required

### CODE REVIEW

**Comment by USERSATOSHI** [comment]
this needs a format change 
check activity.md for example

**Comment by Snipeur060** [comment]
Can you read i change

**Comment by USERSATOSHI** [comment]
usage is wrong 

```php

$reactionCollector[channelId;messageId;userFilters;time;reactions;awaits;removeReaction?; awaitData?;endAwait?]
```

this is the correct usage

**Comment by Snipeur060** [comment]
And now is good or need to update example

**Review by USERSATOSHI — APPROVED** [review]
lgtm

**Pull request merged**
