### PR TITLE
Fixed 5.1.2 documentation!

### PR DESCRIPTION
**Pull request by devmike123**
Added all necessary major changes, missing functions and callbacks to the docs.

### CODE REVIEW

**Comment by devmike123** [comment]
@Leref Its ready to be merged!

**Comment by devmike123** [comment]
I will now be adding descriptions to the functions!

**Comment by devmike123** [comment]
@Leref The pr is ready. All required changes have been added! If there will be more, I will open another pr. Please check it out and merge it.

**Review by Leref — CHANGES_REQUESTED** [review]
All functions should have a preset usage, even if it doesn't have fields, it should always have a usage section.

**Comment by devmike123** [comment]
> All functions should have a preset usage, even if it doesn't have fields, it should always have a usage section.

They have a usage section!

**Comment by devmike123** [comment]
> > All functions should have a preset usage, even if it doesn't have fields, it should always have a usage section.
> 
> They have a usage section!

@Leref

**Comment by devmike123** [comment]
Added $interactionReply function and bot.onInteractionCreate() callback!

**Comment by devmike123** [comment]
@Leref pr ready to be merged!

**Comment by devmike123** [comment]
It's ready to be merged @Leref !

**Comment by devmike123** [comment]
@Leref can you review this pr!

**Comment by Leref** [comment]
There's still several conflicts regarding this Pull request.

**Comment by devmike123** [comment]
@Leref all conflicts resolved!

**Comment by devmike123** [comment]
@Leref pr ready to be merged!

**Comment by devmike123** [comment]
@Leref pr ready to be reviewed!

**Review by Leref — CHANGES_REQUESTED** [review]
A lot of these aren't correct,
Some function usages aren't all added, as well if you need references check the aoi.js src

**Comment by devmike123** [comment]
> A lot of these aren't correct, Some function usages aren't all added, as well if you need references check the aoi.js src

Ok! I will fix them all!

**Comment by Leref** [comment]
You keep reopening this pull request over and over.
It's best to fetch all the changes by making a new fork/updating it.

**Pull request closed without merging**
