### PR TITLE
Create bot.onInteractionCreate.md

### PR DESCRIPTION
**Pull request by DinoTheDevOfficial**
y e s

### CODE REVIEW

**Comment by USERSATOSHI** [comment]
> y e s

actually there is no prototype option for slash commands

prototype is an optional property for buttons only 
@DinoTheDevOfficial

**Comment by DinoTheDevOfficial** [comment]
> > y e s
> 
> actually there is no prototype option for slash commands
> 
> prototype is an optional property for buttons only
> @DinoTheDevOfficial

huh right ill change it

**Comment by USERSATOSHI** [comment]
> > > y e s
> > 
> > actually there is no prototype option for slash commands
> > 
> > prototype is an optional property for buttons only
> > @DinoTheDevOfficial
> 
> huh right ill change it

uh
i meant like u should also add a button example along with SlashCommand

**Comment by DinoTheDevOfficial** [comment]
> > > > y e s
> > > 
> > > 
> > > actually there is no prototype option for slash commands
> > > prototype is an optional property for buttons only
> > > @DinoTheDevOfficial
> > 
> > 
> > huh right ill change it
> 
> uh
> i meant like u should also add a button example along with SlashCommand

wait so prototype is only for buttons and I can remove prototype for slash commands?

**Comment by USERSATOSHI** [comment]
> > > > > y e s
> > > > 
> > > > 
> > > > actually there is no prototype option for slash commands
> > > > prototype is an optional property for buttons only
> > > > @DinoTheDevOfficial
> > > 
> > > 
> > > huh right ill change it
> > 
> > uh
> > i meant like u should also add a button example along with SlashCommand
> 
> wait so prototype is only for buttons and I can remove prototype for slash commands?

yes. lol

**Comment by DinoTheDevOfficial** [comment]
> > > > > > y e s
> > > > > 
> > > > > 
> > > > > actually there is no prototype option for slash commands
> > > > > prototype is an optional property for buttons only
> > > > > @DinoTheDevOfficial
> > > > 
> > > > 
> > > > huh right ill change it
> > > 
> > > 
> > > uh
> > > i meant like u should also add a button example along with SlashCommand
> > 
> > 
> > wait so prototype is only for buttons and I can remove prototype for slash commands?
> 
> yes. lol

lol ight

**Comment by USERSATOSHI** [comment]
@DinoTheDevOfficial after fixing resolve the issues

**Comment by USERSATOSHI** [comment]
@DinoTheDevOfficial where $interactionReply

**Comment by DinoTheDevOfficial** [comment]
> @DinoTheDevOfficial where $interactionReply

ill do it

**Pull request merged**
