### PR TITLE
V5(added missing functions/updated usage)

### PR DESCRIPTION
**Pull request by Neodevils**
Archive thread, this needs to be waited for @USERSATOSHI's merge request on aoi.js v5.1.2

### CODE REVIEW

**Comment by Neodevils** [comment]
@Leref, now it is ready to be merged.

**Comment by Leref** [comment]
If you weren't aware, `SUMMARY.md` must be updated as well for these new functions to appear.

**Comment by Neodevils** [comment]
> 

Sure, we can also update it too.

**Comment by devmike123** [comment]
Your merge has conflicts. Please resolve them!

**Comment by Neodevils** [comment]
@Leref , deleted `./SUMMARY.md` and updated `./src/SUMMARY.md`.

**Comment by Neodevils** [comment]
@Leref-chan, it's open to merge now.

**Review by Leref — APPROVED** [review]
Nice, it looks good!

**Pull request merged**
