### PR TITLE
Changed some stuffs and fixed the code having extra comma which can cause errors

### PR DESCRIPTION
**Pull request by BeastBoyADI**
Changed some stuffs and fixed the code having extra comma which can cause errors

### CODE REVIEW

**Comment by USERSATOSHI** [comment]
u can put , at last property of object tho
doesn't break anything 
¯\_(ツ)_/¯

**Comment by USERSATOSHI** [comment]
it only breaks in json

**Comment by BeastBoyADI** [comment]
Ooo

**Comment by Leref** [comment]
Not needed

**Pull request closed without merging**
