### PR TITLE
Update usddeletemessage.md

### PR DESCRIPTION
**Pull request by Bumblebee-3**

### CODE REVIEW

**Comment by USERSATOSHI** [comment]
update the format according to the contributing example guidelines

**Comment by Bumblebee-3** [comment]
> update the format according to the contributing example guidelines

Hmm. What is left to do?
Its just a typo fix so I don't need to edit summary right?

**Comment by Neodevils** [comment]
> Hmm. What is left to do?
> Its just a typo fix so I don't need to edit summary right?

You also need to update file's format. Which you can find it on contribution template.

**Comment by Bumblebee-3** [comment]
done

**Review by USERSATOSHI — APPROVED** [review]
LGTM

**Pull request merged**
