### PR TITLE
Create customFunctions.md

### PR DESCRIPTION
**Pull request by Bumblebee-3**

### CODE REVIEW

**Comment by DevMike123** [comment]
Good but more explanation is required!

**Comment by Bumblebee-3** [comment]
@DevMike123 Yep will add it now...

**Comment by DevMike123** [comment]
> @DevMike123 Yep will add it now...

Good explanation!

Tell Leref to review the pr!

**Comment by Leref** [comment]
Add into `SUMARRY.md` as well.

**Review by Leref — APPROVED** [review]

**Review by Leref — APPROVED** [review]
Other Pull Request #124, is affiliated with.
Everything checks.

**Pull request merged**
