### PR TITLE
Aoijs v5

### PR DESCRIPTION
**Pull request by USERSATOSHI**
Aoijs V5 Documentation 
this is in work but expect this to come before V5 So people Can Update Their Bot accordingly

### CODE REVIEW

**Comment by Leref** [comment]
For the initial README.md inside of Options
This should be renamed as it'll be
`README.md
-- BotOptions
--etc etc.
`
You could rename it as "Options Guide"

**Comment by USERSATOSHI** [comment]
hmmm so like renaming the file to Option Guide ?

**Comment by Leref** [comment]
On Gitbook it'll be constructed differently.
It'll likely be renamed to something simple to be recognized.

**Comment by USERSATOSHI** [comment]
> On Gitbook it'll be constructed differently.
> It'll likely be renamed to something simple to be recognized.

@Leref can u explain this

cause I didn't understand a thing ;-;

**Review by Leref — APPROVED** [review]
Yes.

**Comment by USERSATOSHI** [comment]
it's not done yet tho

**Comment by USERSATOSHI** [comment]
but this much can work

**Review by Leref — DISMISSED** [review]
Conflicts must be resolved.
Some minor improvements will have to be made before merging.

**Comment by USERSATOSHI** [comment]
ok

**Pull request closed without merging**
