### PR TITLE
Ajout de la partie guildid

### PR DESCRIPTION
**Pull request by Snipeur060**
Il n'était pas renseigné dans le code

### CODE REVIEW

**Comment by USERSATOSHI** [comment]
this needs a format change
please check other files like acitvity.md to match

**Comment by Snipeur060** [comment]
Too long for this function

**Comment by Snipeur060** [comment]
Update to the format change

**Comment by USERSATOSHI** [comment]
contribution guidelines has been changed and because this still doesnt match the previous guidelines' format
i am closing this because @NeoAIChan has already covered this in his pr

**Pull request closed without merging**
