### PR TITLE
Adding Command Handler in callbacks docs

### PR DESCRIPTION
**Pull request by ghost**
Edit: Updated all callbacks docs

### CODE REVIEW

**Comment by USERSATOSHI** [comment]
u could have added them in comamnd handler options lol

**Comment by RileCraft** [comment]
> u could have added them in comamnd handler section lol @RileCraft 

i was planning on doing that but then i was like nah too boring

**Comment by USERSATOSHI** [comment]
command handler section was for that only lol

**Comment by RileCraft** [comment]
> command handler section was for that only lol

well then rip

**Pull request closed without merging**
